# Generated by Django 4.2.15 on 2024-08-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='parent_type',
            field=models.CharField(default='new', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parent',
            name='parent_type',
            field=models.CharField(default='new', max_length=255),
            preserve_default=False,
        ),
    ]
